name: e2e

on: deployment
jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests on preview deployment
        uses: mikefrancis/vercel-cypress@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          repo: my-repo
